### PR TITLE
Fix indentation so ruleset renders better (v2.01)

### PR DESCRIPTION
**Pull request by andylolz**
Refs IATI/IATI-Standard-SSOT#288.

### CODE REVIEW

**Comment by samuele-mattiuzzo** [comment]
@andylolz I can't seem to run `combined_gen.sh` successfully, it shows this traceback

```Notice: No attributes for xsd:string
Traceback (most recent call last):
  File "gen.py", line 556, in <module>
    activities.output_docs('iati-activities', 'activity-standard/')
  File "gen.py", line 263, in output_docs
    self.output_docs(child_name, path+element.attrib['name']+'/', child_element, child_minOccurs, child_maxOccurs, child_ref_element)
  File "gen.py", line 263, in output_docs
    self.output_docs(child_name, path+element.attrib['name']+'/', child_element, child_minOccurs, child_maxOccurs, child_ref_element)
  File "gen.py", line 283, in output_docs
    schema_documentation=textwrap.dedent(self.schema_documentation(element, ref_element)),
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/textwrap.py", line 390, in dedent
    text = _whitespace_only_re.sub('', text)
TypeError: expected string or buffer```

I did replace my local copy of `IATI-Rulesets` with your repo's and switched to this branch

Did you get the same by any chance? Are there any chances you might have made to the `IATI-Standard-SSOT` that would make it work?

**Comment by samuele-mattiuzzo** [comment]
Ah, discard the comment, I copy-pasted the content of `text.py` from your branch into my local copy of Rulesets and now it builds 🤷‍♂️

**Comment by samuele-mattiuzzo** [comment]
Been trying this, it does the job for the element's page

screenshot 2019-02-21 at 10 22 33 am

but then the same rules don't show up for the elements in the rulesets page, showing only empty root elements like

`//budget`

without anything beneath.

It's a start though, will keep on faffing around / trying this! Thanks for the great start Andy! Who'd have thought it was an indentation (hopefully) only issue!

**Comment by andylolz** [comment]
oh right – yeah, L52 looks wrong to me:

https://github.com/IATI/IATI-Rulesets/blob/4dbf425918a4c41a2dd91f8e7f4bae049fb8081f/iatirulesets/text.py#L51-L58

I’ll leave it with you!

**Comment by samuele-mattiuzzo** [comment]
It's taking me a while, but alas I think I have finally understood how this works (and why it does not render).

if `'paths'` is missing in our cases, then it won't bother checking anything at all. So I'm going to use your PR as the base to then perform separate checks for the non - path based rules we have, to have them render properly.

Urgh.

**Comment by samuele-mattiuzzo** [comment]
So! PROGRESS and maybe SUCCESS! @Ocre42 and @andylolz here's what I have done

- started from Andy's PR, which nailed what the issue was
- obviously, because some of our new cases don't use `paths`, they would not print any rule at all.
- made a specific check for those cases and de-idented them like this:

```
if 'paths' in case:
    ...
            else:
                if any(reduced_path in val for val in case.values()):
                    if rule == 'evaluates_to_true':
                        out.append('The conditional expression must evaluate to true.')
                    elif rule == 'date_order' and case['less']:
                        if case['less'] == 'NOW':
                            out.append('``{0}`` must not be in the past.'.format(case['more']))
                        elif case['more'] == 'NOW':
                            out.append('``{0}`` must not be in the future.'.format(case['less']))
                        else:
                            out.append('``{0}`` must be before or the same as ``{1}``'.format(case['less'], case['more']))
                    elif rule == 'time_limit':
                        out.append('The time between ``{0}`` and {1} must not be over a year'.format(case['start'], case['end']))
                    elif rule == 'date_now':
                        out.append('``{0}`` must not be more recent than the current date'.format(case['date']))
                    elif rule == 'if_then':
                        out.append('If ``{0}`` evaluates to true, then ``{1}`` must evaluate to true.'.format(case['if'], case['then']))
                    elif rule == 'one_or_all':
                        out.append('``{0}`` must exist, otherwise all ``{1}`` must exist.'.format(case['one'], case['all']))
                    elif rule == 'evaluates_to_true':
                        out.append('Each expression defined in ``{0}`` must resolve to true.'.format(case['eval']))
                    elif rule == 'between_dates':
                        out.append('The ``{0}`` must be between the ``{1}`` and ``{2}`` dates.'.format(case['date'],case['start'],case['end']))
                    elif rule == 'loop':
                        out.append('All elements in ``{0}`` are evaluated under the rules inside ``{1}``.'.format(case['foreach'],case['do']))
                else:
                    print('Not implemented', rule, case)
```

this does both populate all rules in the correct Ruleset page and only applies those relevant to the element in its specific page.

(FYI: I'm out of office tomorrow, so it'll be fixed on Monday properly... although I know I won't resist tomorrow and will most likely do it :P)

If all 3 of us could take a quick look and confirm it actually works, then I'll proceed!

**Comment by andylolz** [comment]
> obviously, because some of our new cases don't use `paths`, they would not print any rule at all.

^^ Aha! Great spot! 🔍 

```python
if any(reduced_path in val for val in case.values()):
```

^^ One thing is: I thiiiiink this still needs to check `show_all`? Is that true? I.e.

```python
if show_all or any(reduced_path in val for val in case.values()):
```

The other thing to mention is… `case.values()` may contain non-path-like things, so while this probably works, it is a tiny bit dodgy… but as long as the comment you’ve added is there, I think it’s okay :shipit:

**Comment by samuele-mattiuzzo** [comment]
@andylolz my thoughts exactly, dodgy indeed!

**Pull request merged**
