### PR TITLE
Fix result value rules

### PR DESCRIPTION
**Pull request by andylolz**
#55 adds untested rules to `version-2.03dev`. This PR adds tests for these new rules, which initially failed. It then patches the bugs, so that the tests pass.

This should be addressed before merging `version-2.03dev` to `version2.03`.

---

Refs #61.

### CODE REVIEW

**Comment by andylolz** [comment]
But… Why doesn’t this use [condition](https://github.com/IATI/IATI-Rulesets/blob/c33d11885e1084bb99d897c9a5dc3bfcea91c0fb/iatirulesets/__init__.py#L83)?

**Comment by hayfield** [comment]
> But… Why doesn’t this use condition?

The [Ruleset Spec](http://iatistandard.org/202/rulesets/ruleset-spec/) states that at `condition` is: `An xpath string. If this evaluates to True, the rule will be ignored.`

As such, it's a condition to skip the Rule rather than to progress with the Rule.

@Bjwebb has noted that this is the inverse to what may be expected.

**Comment by andylolz** [comment]
> @Bjwebb has noted that this is the inverse to what may be expected.

It’s certainly the inverse of what I’d expect. Unless I am very muddled up, it also appears to be the inverse of what it actually does:
https://github.com/IATI/IATI-Rulesets/blob/c33d11885e1084bb99d897c9a5dc3bfcea91c0fb/iatirulesets/__init__.py#L83

**Comment by andylolz** [comment]
I wonder if:

```
@measure != 5
```

…is perhaps clearer than:

```
@measure = 1 or @measure = 2 or @measure = 3 or @measure = 4
```

Wdyt?

**Comment by Bjwebb** [comment]
> Unless I am very muddled up, it also appears to be the inverse of what it actually does: `IATI-Rulesets/iatirulesets/__init__.py`

Yes that's correct. I'm pretty sure the code does what I intended, and that I got the Spec wrong. Sorry :/

**Pull request merged**
