### PR TITLE
Fix output text for "none of" rules (v2.03)

### LINKED ISSUE #227: Human-readable output of activity-date rules are unclear (and don’t mention the condition)
On the [activity-date page](http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/activity-date/) of the reference site:

Screenshot 2019-09-20 at 09 53 46

I’m also unsure where these rules come from. They don’t seem to be mentioned in the new (or old) guidance here:
http://reference.iatistandard.org/203/activity-standard/overview/dates/

### PR DESCRIPTION
**Pull request by andylolz**
Fixes #227.

[Demo here](http://227-none-of-iati-rulesets-refbot.surge.sh/activity-standard/iati-activities/iati-activity/activity-date/):

Screenshot 2019-09-20 at 13 30 25

### CODE REVIEW

**Comment by andylolz** [comment]
@referencebot build

**Comment by andylolz** [comment]
@referencebot build

**Comment by samuele-mattiuzzo** [comment]
Thanks Andy! I might hold on the merge just yet as we're discussing whether those two extra checks are actually meant to be in there or not!

**Comment by andylolz** [comment]
Makes sense.

These rules were added recently (earlier this year), as a result of this discussion:
https://discuss.iatistandard.org/t/relationship-between-activity-status-and-activity-date-s/1679

**Comment by nosvalds** [comment]
Hi @samuele-mattiuzzo and @andylolz is this PR still relevant? I'm working to clean up this repo and extraneous branches. Let me know before 30 Oct 2020 or I'll just close this PR.

**Comment by samuele-mattiuzzo** [comment]
I must admit I have no memory where the conversation ended with this, apologies

**Comment by andylolz** [comment]
I suspect this code is no longer in use. I think @akmiller01 would know if that’s the case or not.

It looks like the rules that this PR references have been removed from the ruleset? I don’t see them in the new ruleset that the new validator uses:
https://github.com/data4development/IATI-Rulesets/tree/b90104f4b4576c81db9fe7bf3a37e7d5a41757b0/rules/iati

**Comment by andylolz** [comment]
Hi @nosvalds – thanks for getting in touch.

I suspect this code is no longer in use. I think @akmiller01 would know if that’s the case or not.

It looks like the rules that this PR references have been removed from the ruleset? I don’t see them in the new ruleset that the new validator uses:
https://github.com/data4development/IATI-Rulesets/tree/b90104f4b4576c81db9fe7bf3a37e7d5a41757b0/rules/iati

**Comment by akmiller01** [comment]
It still should be used in the generation of the SSOT content on the main website; we can give it a rebase and see if it's still valid with the main version branch.

**Comment by andylolz** [comment]
@akmiller01 Oh wow, okay – I hadn’t realised how much the default branch of this repo had changed!

Yeah, I don’t think this makes any sense in the context of `master`.

Not really related, but: I notice the validator appears to point at **a fork of** this repo, rather than this repo:
https://github.com/IATI/IATI-Validator-Actual/tree/23b30f27/lib

Is that intentional? Should that be updated?

**Comment by nosvalds** [comment]
@andylolz yes we did notice last week investigating a validator issue that the validator is pointing to the d4d fork of IATI-Rulesets repo rather than this repo. We're working on fixing it and plan to include the update in the next update of the validator. 

@akmiller01 that makes sense if this is how we want the documentation reflected. How does it look after the rebase to you?

**Comment by andylolz** [comment]
@akmiller01 says:
> It still should be used in the generation of the SSOT content on the main website

Do you mean the `master` branch of this repo? If so, I’m not able to find that code.

---

@andylolz says:
> One thing that it would be worth investigating… It looks like the rules that this PR references have been removed from the ruleset? I don’t see them in the new ruleset that the new validator uses:
> https://github.com/data4development/IATI-Rulesets/tree/b90104f4b4576c81db9fe7bf3a37e7d5a41757b0/rules/iati

^^ I’d forgotten that I’d already raised this issue here: data4development/IATI-Rulesets#60.

**Comment by akmiller01** [comment]
> Do you mean the `master` branch of this repo? If so, I’m not able to find that code.

Each respective version branch of the SSOT contains a submodule reference to the version branch of the IATI-Rulesets repo, that's used in the RST generation process: https://github.com/IATI/IATI-Standard-SSOT/blob/version-2.03/gen.py#L9

**Comment by andylolz** [comment]
@akmiller01 Thanks. Right, I see. So that’s also how it worked before the reference site migration, and before the new validator launch.

This all seems to be in a bit of an in-between state. The README for this repo says:
> As part of the Validator work, the earlier JSON-based rules have been migrated to an XSLT-based system, and some additional checks and feedback messages have been added.

Correct me if I’m wrong, but I don’t think it’s correct to suggest that this migration is complete. The reference site is still using the JSON-based rules on the version branches, and the validator is pointing at a fork of this repo.

**Comment by samuele-mattiuzzo** [comment]
@andylolz and @akmiller01 I missed these conversations oh so much! Not even joking here (sorry for the off topic by the way)!
:heart:

**Comment by andylolz** [comment]
@akmiller01 says:
> It still should be used in the generation of the SSOT content on the main website; we can give it a rebase and see if it's still valid with the main version branch.

Okay so I think “main version branch” here refers to `version-2.03` (as opposed to `master`. Sorry, I got confused because many repos now use `main` to indicate their default branch).

I’ve brought this branch up-to-date against `version-2.03`. Since it sounds like this code is still in use for generating the reference site, I think this PR is still relevant, so I’ll leave it open.

Thanks all.

**Comment by nosvalds** [comment]
@andylolz yes this makes sense now and I agree this PR is needed because the way these rules are currently showing "not(" something is not user friendly. 

I'll work on doing some testing and review/merge.

**Comment by nosvalds** [comment]
See the last 3 lines in the Rules section. @IATI/bas can you confirm this looks good to you or if you have any comments? Then I'll work with @akmiller01 on a deployment plan.

- Before:
image


- After: 

image

**Comment by amy-silcock** [comment]
@nosvalds shouldn't the example match the code here: https://github.com/IATI/IATI-Rulesets/pull/236

The rules don't link activity-date to activity-status (though this is super logical and would be good to add at v.3). For now they just ensure the dates are in the past or 'now'?

**Comment by nosvalds** [comment]
Hey @andylolz I've double checked with the BAs and we all agree that these rules make sense logically, however they shouldn't have been added into the standard until there was an upgrade. 

We could not confirm that they were officially approved in an upgrade previously (https://github.com/IATI/IATI-Rulesets/pull/159). 

The BAs will add this to the list of things to add for v.3.

**Comment by andylolz** [comment]
The relevant [discuss discussion](https://discuss.iatistandard.org/t/relationship-between-activity-status-and-activity-date-s/1679) is linked in this issue: #158.

I’m afraid I don’t know what the official process is for adding or amending ruleset rules. Is there one? Does this sort of change definitely have to wait for a major version upgrade?

**Comment by amy-silcock** [comment]
Hi Andy, adding in a rule that previously published data may break is a major upgrade addition. We're hoping that the next upgrade (whenever it happens) will be a major one.

**Comment by andylolz** [comment]
> adding in a rule that previously published data may break is a major upgrade addition. 

Previously published data could break *any* new rule. So I think that would mean rules can only be introduced at major upgrades?

I’ve had a look in the [upgrade process](https://iatistandard.org/en/iati-standard/upgrades/how-we-manage-the-standard/upgrade-process/) and [previous upgrade process](https://iatistandard.org/en/iati-standard/upgrades/how-we-manage-the-standard/previous-process/), and I don’t think a process for adding rules is documented.

Worth noting that other rules have been introduced between upgrades, so there is form for this. For instance, `recipient-country-budget`’s “budget line value date must be within the budget period” [[ref](https://github.com/IATI/IATI-Rulesets/blob/acf67d0a611db0ac02a9dd5f7b789fd0dbf1807d/rules/iati/dates.xslt#L87-L98)] was added in #124. The source provided for that rule is [this document](https://drive.google.com/file/d/1mv2Q666tKBOAoiy5JayslmZNetxDM1uu/view), but I don’t see the rule mentioned there.

I suppose the important thing here is how these rules will be applied. If they’re used to provide informative messages to publishers and users that there’s an issue (and not to block import of data) then the more, the better.

**Comment by andylolz** [comment]
> adding in a rule that previously published data may break is a major upgrade addition. 

Previously published data could break *any* newly introduced ruleset rule. So I think that would mean ruleset rules can only be introduced at major upgrades?

I’ve had a look in the [upgrade process](https://iatistandard.org/en/iati-standard/upgrades/how-we-manage-the-standard/upgrade-process/) and [previous upgrade process](https://iatistandard.org/en/iati-standard/upgrades/how-we-manage-the-standard/previous-process/), and I don’t think a process for adding rules is documented.

Worth noting that other rules have been introduced between upgrades, so there is form for this. For instance, `recipient-country-budget`’s “budget line value date must be within the budget period” [[ref](https://github.com/IATI/IATI-Rulesets/blob/acf67d0a611db0ac02a9dd5f7b789fd0dbf1807d/rules/iati/dates.xslt#L87-L98)] was added in #124. The source provided for that rule is [this document](https://drive.google.com/file/d/1mv2Q666tKBOAoiy5JayslmZNetxDM1uu/view), but I don’t see the rule mentioned there.

I suppose the important thing here is how these rules will be applied. If they’re used to provide informative messages to publishers and users that there’s an issue (and not to block import of data) then the more, the better.

**Comment by amy-silcock** [comment]
Hi Andy,

You're right that IATI hasn't always followed it's own processes, nor have the processes been robust. Rules are a way of us checking whether or not a publisher is adhering to the Standard. 

Therefore, the rules follow the descriptions written in the schema (except for some of the early ones). The 'new ones' added above, exist in the schema descriptions but hadn't made their way into the 'rules'. 

To add a new rule, means we need to change the schema as part of an upgrade: https://iatistandard.org/en/iati-standard/upgrades/how-we-manage-the-standard/upgrade-process/. Hence we run into backwards compatibility, we can add MUST statements for new elements but not to existing ones without a major upgrade.

Happy to speak more in person if helpful and hoping to tidy this all up when we get to do a major upgrade!

**Comment by andylolz** [comment]
Thanks @amy-silcock. That clarifies a few things.

The relationship between `activity-date` and `activity-status` does have some grounding in the standard documentation. The following sentence has been [part of the standard](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/activity-date/#example-usage) since v1.04:

> Note: In some cases, not all _ActivityDateType_ codes can be declared, depending on the `activity-status` of the `iati-activity`

Conversely, there are a number of rules in the standard ruleset that are not mentioned in the standard documentation. For example, the recently added `budget-line` rule has no grounding in the standard documentation.

But let’s focus on moving this pull request forward. The rules it references have been dropped as part of the move to the new ruleset format. However, these rules still appears in the documentation, because the documentation is generated from the old ruleset code.
Screenshot 2020-11-10 at 16 04 40

So there are three options for resolving this:
 1. Generate the documentation from the new ruleset format
 2. Remove the rules from the old ruleset format, and close this PR
 3. Add the rules back in to the new ruleset format, and merge this PR

Option 1 is a sizeable chunk of work. It doesn’t sound like you are keen on option 3. So is option 2 the way to go?

**Comment by andylolz** [comment]
Aha – I hadn’t spotted #237, which update the rules in the old ruleset format to better match the new ones, by removing these `activity-date`/`activity-status` rules.

So given that PR, I think this one is closable. Thanks all

**Pull request closed without merging**
