### PR TITLE
Fix `@xml:lang` bug (version 2.03)

### PR DESCRIPTION
**Pull request by andylolz**
`@xml-lang` is the wrong attribute name. It should be `@xml:lang`.

### CODE REVIEW

**Comment by andylolz** [comment]
Needs replicating for other branches (I’m not going to do that.)

**Comment by andylolz** [comment]
(Just to explain: I’m not going replicate to other branches because I don’t know if this fix will be merged yet, so it could potentially be wasted work. If someone approves this PR and asks for the fix to be applied to v2.01 and v2.02, I’ll happily do it.)

**Comment by samuele-mattiuzzo** [comment]
@Ocre42 and @sargentfrancesca can you both take a look at this, even with @amy-silcock if needs more clarification, and then proceed as usual? thank you 👏

**Comment by andylolz** [comment]
@sargentfrancesca no problem. See: #180 & #181.

**Pull request merged**
