### PR TITLE
Update codelists and schema used by iati.xslt from sources of truth

### PR DESCRIPTION
**Pull request by nosvalds**
This PR updates the codelists and schemas in the /lib/ directory from their maintained sources of truth. The Validator relies on these codelists and schemas. 

`lib/schemata/non-embedded-codelist/`
  - source of truth: [IATI/IATI-Codelists-NonEmbedded](https://github.com/IATI/IATI-Codelists-NonEmbedded) (master) / xml

`lib/schemata/2.03/`
- `iati-activities-schema.xsd`
- `iati-common.xsd`
- `Iati-organisations-schema.xsd`

  - source of truth: [IATI/IATI-Schemas](https://github.com/IATI/IATI-Schemas/tree/version-2.03) (version-2.03)

`lib/schemata/2.03/codelist/*.xml`

  - source of truth:[ IATI/IATI-Codelists](https://github.com/IATI/IATI-Codelists) / xml (version-2.03)

### CODE REVIEW

**Comment by nosvalds** [comment]
Added an additional commit after syncing all the available versions available from the sources of truth.

This was done using a new .sh script in the [IATI-Standard-SSOT](https://github.com/IATI/IATI-Standard-SSOT ) repository `update_rulesets_lib.sh`

Note `xml.xsd` had to be added in each `lib/schemata/X.XX/` version directory due to that being how it's referenced in the .xsd files in the IATI-Schema repo.

**Review by akmiller01 — APPROVED** [review]
:shipit:

**Comment by nosvalds** [comment]
FYI I did a check of running the tests and get the same result as before these changes. (there are 3 failing). We can look into that separately:

## master branch:
image

## this branch:
image

**Comment by nosvalds** [comment]
Hey @IATI/bas if you could take a look at the changes and let me know if anything looks off that would be great!

**Review by amy-silcock — APPROVED** [review]

**Pull request merged**
